// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKQWfCTtKltB3FG9CK6YudA_qI_p9EnlE',
    appId: '1:859623356146:web:a11470a52467910468c26b',
    messagingSenderId: '859623356146',
    projectId: 'byu-ais-hackathon',
    authDomain: 'byu-ais-hackathon.firebaseapp.com',
    databaseURL: 'https://byu-ais-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'byu-ais-hackathon.appspot.com',
    measurementId: 'G-5Q4PPT9WKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvizAdbd90Xdai_iegRsGiX-Obheh6Ado',
    appId: '1:859623356146:android:cb35358b97b7485268c26b',
    messagingSenderId: '859623356146',
    projectId: 'byu-ais-hackathon',
    databaseURL: 'https://byu-ais-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'byu-ais-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUnoSCo3mU-NjePvixkim6DHNlV3qul7c',
    appId: '1:859623356146:ios:b5fd1b2cd30dfa2268c26b',
    messagingSenderId: '859623356146',
    projectId: 'byu-ais-hackathon',
    databaseURL: 'https://byu-ais-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'byu-ais-hackathon.appspot.com',
    iosBundleId: 'com.example.aisHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUnoSCo3mU-NjePvixkim6DHNlV3qul7c',
    appId: '1:859623356146:ios:0b15363824f73c5368c26b',
    messagingSenderId: '859623356146',
    projectId: 'byu-ais-hackathon',
    databaseURL: 'https://byu-ais-hackathon-default-rtdb.firebaseio.com',
    storageBucket: 'byu-ais-hackathon.appspot.com',
    iosBundleId: 'com.example.aisHackathon.RunnerTests',
  );
}
